# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Estimates — Send quotes, focus on creative work
description:        Estimates – Send quotes, focus on creative work

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://estimates.ai"

# Site logo, image or text
brand:
    image:          estimates-logo.svg  # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           Estimates      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Default author settings
author:
    name:       Louis Rouffineau
    github:     lourou    # Github username for avatar

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    louis:
        name:       Louis Rouffineau
        github:     lourou    # Github username for avatar
    gwenth:
        name:       Gwenaëlle
        github:     gwenth    # Github username for avatar

# Social icons displayed in footer
social:
    email:          mai&#108;to&#58;%63on&#116;%61%63t%40est&#105;m&#37;6&#49;&#116;e%&#55;&#51;&#46;&#37;6&#49;%69         
    website:        https://estimates.ai
    facebook:       
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      
    linkedin:
    pinterest:
    twitter:        https://twitter.com/louisrouffineau
    vimeo:          
    youtube:

# Twitter share button
twitter_username: louisrouffineau

# Default footer image settings
footer:
    copyright:      Made in France 🇫🇷while eating 🧀🥖and 🥐

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics: UA-117557871-1

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key: AIzaSyAMJ2a9h_JPocUjk2ohnoMAk6Ep1jtbMx4

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "/journal/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style: compressed
  sourcemap: auto

collections:
  docs:
    output: true
